---

- name: Настройка групповых политик паролей | Пароль должен отвечать требованиям сложности
  ansible.builtin.command: samba-tool domain passwordsettings set --complexity={{ complexity }}
  register: pass_set
  changed_when: pass_set.rc != 0


- name: Настройка групповых политик паролей | Хранить пароли используя обратимое шифрование
  ansible.builtin.command: samba-tool domain passwordsettings set --store-plaintext={{ store_plaintext }}
  register: pass_set
  changed_when: pass_set.rc != 0


- name: Настройка групповых политик паролей | Число хранимых предыдущих паролей пользователей
  ansible.builtin.command: samba-tool domain passwordsettings set --history-length={{ history_length }}
  register: pass_set
  changed_when: pass_set.rc != 0


- name: Настройка групповых политик паролей | Минимальное количество символов в пароле
  ansible.builtin.command: samba-tool domain passwordsettings set --min-pwd-length={{ min_pwd_length }}
  register: pass_set
  changed_when: pass_set.rc != 0


- name: Настройка групповых политик паролей | Минимальный срок действия пароля
  ansible.builtin.command: samba-tool domain passwordsettings set --min-pwd-age={{ min_pwd_age }}
  register: pass_set
  changed_when: pass_set.rc != 0


- name: Настройка групповых политик паролей | Максимальный срок действия пароля
  ansible.builtin.command: samba-tool domain passwordsettings set --max-pwd-age={{ max_pwd_age }}
  register: pass_set
  changed_when: pass_set.rc != 0


- name: Настройка групповых политик паролей | Собрать текущие параметры политик
  ansible.builtin.command: samba-tool domain passwordsettings show
  register: pass_set
  changed_when: pass_set.rc != 0

- name: Настройка групповых политик паролей | Показать текущие параметры политик
  ansible.builtin.debug:
   msg: "{{ pass_set.stdout_lines }}"