---

- name: Set a hostname
  hostname:
   name: "{{new_dc_hostname }}"

- name: Check netplan file
  find:
   paths: "/etc/netplan"
   patterns: "*.yaml"
  register: netplan_check_config

- name: Replace netplan config
  template:
   src: netplan_config.j2
   dest: "{{ netplan_check_config.files[0].path }}"
   mode: 0644
   backup: yes
  notify: 
   Netplan apply config
